import type { CaseSummary } from '@/types/intake';

interface ExportOptions {
  language: 'tr' | 'en';
}

export function generatePdfHtml(summary: CaseSummary, options: ExportOptions): string {
  const { language } = options;
  const isEnglish = language === 'en';

  const labels = isEnglish
    ? {
        title: 'Case Summary',
        caseId: 'Case ID',
        createdAt: 'Created At',
        disputeType: 'Dispute Type',
        parties: 'Parties Involved',
        initiator: 'Initiating Party',
        respondent: 'Other Party',
        coreThemes: 'Core Themes Identified',
        neutralSummary: 'Neutral Summary',
        keyIssues: 'Key Issues to Address',
        pathways: 'Potential Resolution Pathways',
        disclaimer: 'Reminder: This summary is a preparation tool, not legal advice. Any resolution reached through mediation is the decision of the parties involved.',
        generatedBy: 'Generated by MediationPath',
      }
    : {
        title: 'Dava Özeti',
        caseId: 'Dosya No',
        createdAt: 'Oluşturulma Tarihi',
        disputeType: 'Uyuşmazlık Türü',
        parties: 'Taraflar',
        initiator: 'Başvuran Taraf',
        respondent: 'Diğer Taraf',
        coreThemes: 'Temel Temalar',
        neutralSummary: 'Tarafsız Özet',
        keyIssues: 'Ele Alınacak Temel Konular',
        pathways: 'Potansiyel Çözüm Yolları',
        disclaimer: 'Hatırlatma: Bu özet bir hazırlık aracıdır, hukuki danışmanlık değildir. Arabuluculuk yoluyla ulaşılan herhangi bir çözüm, ilgili tarafların kararıdır.',
        generatedBy: 'MediationPath tarafından oluşturuldu',
      };

  const formatDate = (date: Date) => {
    return new Intl.DateTimeFormat(isEnglish ? 'en-US' : 'tr-TR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(date);
  };

  return `
<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${summary.id}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #ffffff;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      text-align: center;
      border-bottom: 2px solid #4F46E5;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #4F46E5;
      font-size: 28px;
      margin-bottom: 10px;
    }
    .meta-info {
      display: flex;
      justify-content: center;
      gap: 30px;
      color: #6b7280;
      font-size: 14px;
    }
    .section {
      margin-bottom: 25px;
    }
    .section-title {
      font-size: 12px;
      font-weight: 600;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 8px;
    }
    .section-content {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
    }
    .parties-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }
    .party-box {
      background: #ffffff;
      border: 1px solid #e5e7eb;
      border-radius: 6px;
      padding: 12px;
    }
    .party-label {
      font-size: 11px;
      color: #9ca3af;
      margin-bottom: 4px;
    }
    .party-name {
      font-weight: 600;
      color: #1f2937;
    }
    .themes-list {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }
    .theme-tag {
      background: #EEF2FF;
      color: #4F46E5;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 13px;
    }
    .issues-list, .pathways-list {
      list-style: none;
    }
    .issues-list li, .pathways-list li {
      padding: 8px 0;
      border-bottom: 1px solid #e5e7eb;
      display: flex;
      align-items: flex-start;
      gap: 10px;
    }
    .issues-list li:last-child, .pathways-list li:last-child {
      border-bottom: none;
    }
    .issue-number {
      width: 24px;
      height: 24px;
      background: #EEF2FF;
      color: #4F46E5;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
      font-weight: 600;
      flex-shrink: 0;
    }
    .pathway-arrow {
      color: #4F46E5;
      flex-shrink: 0;
    }
    .disclaimer {
      margin-top: 40px;
      padding: 16px;
      background: #FEF3C7;
      border: 1px solid #FCD34D;
      border-radius: 8px;
      font-size: 13px;
      color: #92400E;
    }
    .footer {
      margin-top: 30px;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
    @media print {
      body {
        padding: 20px;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${labels.title}</h1>
    <div class="meta-info">
      <span><strong>${labels.caseId}:</strong> ${summary.id}</span>
      <span><strong>${labels.createdAt}:</strong> ${formatDate(summary.createdAt)}</span>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.disputeType}</div>
    <div class="section-content">
      <strong>${summary.disputeType}</strong>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.parties}</div>
    <div class="section-content">
      <div class="parties-grid">
        <div class="party-box">
          <div class="party-label">${labels.initiator}</div>
          <div class="party-name">${summary.parties.initiator}</div>
        </div>
        <div class="party-box">
          <div class="party-label">${labels.respondent}</div>
          <div class="party-name">${summary.parties.respondent}</div>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.coreThemes}</div>
    <div class="section-content">
      <div class="themes-list">
        ${summary.coreThemes.map((theme) => `<span class="theme-tag">${theme}</span>`).join('')}
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.neutralSummary}</div>
    <div class="section-content">
      <p>${summary.neutralSummary}</p>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.keyIssues}</div>
    <div class="section-content">
      <ul class="issues-list">
        ${summary.keyIssues.map((issue, index) => `
          <li>
            <span class="issue-number">${index + 1}</span>
            <span>${issue}</span>
          </li>
        `).join('')}
      </ul>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${labels.pathways}</div>
    <div class="section-content">
      <ul class="pathways-list">
        ${summary.potentialPathways.map((pathway) => `
          <li>
            <span class="pathway-arrow">→</span>
            <span>${pathway}</span>
          </li>
        `).join('')}
      </ul>
    </div>
  </div>

  <div class="disclaimer">
    <strong>⚠️</strong> ${labels.disclaimer}
  </div>

  <div class="footer">
    ${labels.generatedBy} • ${formatDate(new Date())}
  </div>
</body>
</html>
  `;
}

export function exportToPdf(summary: CaseSummary, language: 'tr' | 'en' = 'tr'): void {
  const html = generatePdfHtml(summary, { language });
  
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    
    // Wait for content to load before printing
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

export function downloadAsHtml(summary: CaseSummary, language: 'tr' | 'en' = 'tr'): void {
  const html = generatePdfHtml(summary, { language });
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `case-summary-${summary.id}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
